### ISSUE TITLE
Trying to checkout bitbucket repo throws an error

### ISSUE THREAD

**Issue by ntshshvnkr** [cloudbees-io/checkout#24]
Hi Team,

I am trying to checkout a bitbucket repository using Cloudbees Platform(cloudbees.io).
I have integrated the repo successfully using PAT.

While running workflow I am getting below error.

transform workflow to tekton: workflow My workflow job build: steps[1]: load action "CheckOutTaggingService": resolve nested action "cloudbees-io/checkout@v1": open /tmp/bitbucket.org/cloudbees-io/checkout/version/v1/no-sha/action.yaml: no such file or directory
3 get scm token: [POST /reserved/v1/resources/{resourceId}/scm-access-token][403] AutomationScmService_GetAutomationAccessTokenForSCMRepo default  &{Code:7 Details:[] Message:permission denied}

Thanks in advance.

**Comment by pinaki124** [comment]
> cloudbees-io/checkout@v1"

Hi @ntshshvnkr - Since you are checking out a Bitbucket repo and invoking an action which lives in GitHub you will need to provide the fully qualified URL, in this case call the action as `https://github.com/cloudbees-io/checkout@v1` in the `uses` field.
